//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalReplicaScaler) DeepCopyInto(out *HorizontalReplicaScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalReplicaScaler.
func (in *HorizontalReplicaScaler) DeepCopy() *HorizontalReplicaScaler {
	if in == nil {
		return nil
	}
	out := new(HorizontalReplicaScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorizontalReplicaScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalReplicaScalerList) DeepCopyInto(out *HorizontalReplicaScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HorizontalReplicaScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalReplicaScalerList.
func (in *HorizontalReplicaScalerList) DeepCopy() *HorizontalReplicaScalerList {
	if in == nil {
		return nil
	}
	out := new(HorizontalReplicaScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorizontalReplicaScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalReplicaScalerSpec) DeepCopyInto(out *HorizontalReplicaScalerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalReplicaScalerSpec.
func (in *HorizontalReplicaScalerSpec) DeepCopy() *HorizontalReplicaScalerSpec {
	if in == nil {
		return nil
	}
	out := new(HorizontalReplicaScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalReplicaScalerStatus) DeepCopyInto(out *HorizontalReplicaScalerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalReplicaScalerStatus.
func (in *HorizontalReplicaScalerStatus) DeepCopy() *HorizontalReplicaScalerStatus {
	if in == nil {
		return nil
	}
	out := new(HorizontalReplicaScalerStatus)
	in.DeepCopyInto(out)
	return out
}
