# permissions for end users to edit horizontalreplicascalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: horizonalreplicascaler
    app.kubernetes.io/managed-by: kustomize
  name: horizontalreplicascaler-editor-role
rules:
- apiGroups:
  - scaling.rrethy.com
  resources:
  - horizontalreplicascalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.rrethy.com
  resources:
  - horizontalreplicascalers/status
  verbs:
  - get
