# permissions for end users to view horizontalreplicascalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: horizonalreplicascaler
    app.kubernetes.io/managed-by: kustomize
  name: horizontalreplicascaler-viewer-role
rules:
- apiGroups:
  - rrethy.com.rrethy.com
  resources:
  - horizontalreplicascalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rrethy.com.rrethy.com
  resources:
  - horizontalreplicascalers/status
  verbs:
  - get
