---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scaling.rrethy.com
  resources:
  - horizontalreplicascalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.rrethy.com
  resources:
  - horizontalreplicascalers/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.rrethy.com
  resources:
  - horizontalreplicascalers/status
  verbs:
  - get
  - patch
  - update
